# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3de0deb2ab308b45cb6fcab57be41739e8bca67f11d160a92f6d25494c2de9d0b247e0eb7fe5c77b916b248288dab422ad5c41d6db090dc0df77b1855d161520

test:
  secret_key_base: 84df16d1f3d23bb42d2010c49de7375a397918769273e42166810ace8b5ab0fee6d519760e41c95864757992fe908b465646a53dca0e5d27df4990c8ccd8d3c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
